---
- hosts: all
  roles:
      - { role: service1, sb_src_url: "https://search.maven.org/remotecontent?filepath=org/robolectric/junit/3.8/junit-3.8.jar" }
      - { role: service2,
         sb_app_name: "service2",
         sb_src_file: "../service2/service2.jar", spring_kafka_bootstrap_servers: "s00vl9983599.fr.net.intra:9092" }